spring.application.name=VaultTrackBackend

spring.config.import=optional:file:.env[.properties]

# Postgres Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/VaultTrackDB
spring.datasource.username=postgres
spring.datasource.password=killmakarov

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=762cce42a6e8207c754103b43d51946ee00fec595168f812a4ae95a3efa2a2d5
jwt.expiration=172800000
